site_name: Team Documentation
site_description: Documentation for our awesome team
site_author: Your Name
theme: landing
nav:
 - Home: index.md
 - About: about.md
 - Guidelines: guidelines.md
